### ISSUE TITLE
Palindrome checker case insensitive doesn't work right

### ISSUE THREAD

**Issue by Jacob-Lockwood** [kudadam/kudadam.com#7]
When you use the palindrome checker with a word that is a palindrome but has capital and lowercase letters, the program does not work properly.
Example:
```
word : Tacocat
case sensitive : false
ignore whitespaces : false

1.We will start by putting your word in a container called A.
A = [tacocat]

...

7.We then compare both containers A and B.
A = [tacocat] B= [tacocat].

8. The letters in container A are different from the one in container B.
So 'tacocat' is not a palindrome.😄
```
You can clearly see that container A and container B contain the exact same text, but the program still says they are different.

**Comment by lubiah** [comment]
Hey @skra-pa-pa, thanks for informing me, I will check and fix the bug right now

**Comment by lubiah** [comment]
Hey @skra-pa-pa , bug has been fixed
